services:
  redis:
    image: redis:latest
    container_name: my-redis
    restart: always
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: my-web-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - redis
